### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by terrorist96** [wasdennnoch/Scoop#1]
When you get a notification of a crash, could you add an option so that when you 'expand' the notification, there are options we can select, such as 'copy to clipboard' or the generic 'share' button? This way, it skips the step of opening the app.
Thanks for maintaining this module. I've removed Cracker now. 😃

**Comment by wasdennnoch** [comment]
Will add that when I'm done flashing / installing Nougat :)
I don't have Xposed anymore though, but a small UI change doesn't require Xposed.

**Comment by wasdennnoch** [comment]
Done. Will update the version soon. Merry christmas :)

**Comment by wasdennnoch** [comment]
Available in v1.2.0.
