### ISSUE TITLE
Crashes From Google Newsstand Going Unnoticed

### ISSUE THREAD

**Issue by hexxellor** [wasdennnoch/Scoop#3]
I'm experiencing crashes in Google Newsstand. I have attached a log of the crash which Scoop doesn't notice. It appears to be when it fails to get an ad or something it really wants for offline reading. Once it crashes it _usually_ restarts the application but not always. Am I mistaken that, with nothing blacklisted and the option to ignore Thread Death turned off, it should be catching these?

[2017-01-15_10-22-09.crash.txt](https://github.com/wasdennnoch/Scoop/files/718616/2017-01-15_10-22-09.crash.txt)

**Comment by wasdennnoch** [comment]
Is this the full log or a filtered/shortened version? There seem to be some random logs in there, that's why I'm asking. I'll have a deeper look later this day.

**Comment by hexxellor** [comment]
It was everything logged by 3C Toolbox when the application (Newsstand) was executed. If I recall correctly it crashed a couple times before I could close it completely and get the log. Is that what you mean? If it's not enough just let me know and I'll see what I can do.

**Comment by wasdennnoch** [comment]
I mean this this isn't a full log but a filtered one where only sertain lines are captured. I don't know about the default setting sof 3C Toolbox, but to get a better log quickly you can install MatLog; it's a continuation of the famous catlog app which was specificially made to capture the logcat and it doesn't apply any filter per default. (Or you dig through the 3C settings)

**Comment by hexxellor** [comment]
Just a quick note that I'm not ignoring this, I just happen to have switched phones now so I'll see if it happens on the new one too and then let you know.

**Comment by wasdennnoch** [comment]
Take your time, but either way please post a full logcat as I described. The current one contains multiple chopped stack traces and some infos of a native crash which I can't catch with the module (or which you can't catch in general without modifying the original c(++) code).

**Comment by hexxellor** [comment]
Well, I hate to do this but I haven't had Newsstand crash on the new phone I'm using with a recent version of Android. The old phone was on some crazy old version like 4.4.2. 😱  

I'll close this for now and you can do what you want with it. If I do end up getting any more of the crashes in the future I'll let you know (with a better log). Sorry about that.

BTW, great work on the Xposed module. It's very handy. 👍

**Comment by wasdennnoch** [comment]
Be happy that to doesn't crash anymore :P
Thanks!
