### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by malitech** [wasdennnoch/Scoop#5]
The files in the /data/system/dropbox folder are 0 bytes. I want to find some errors and this module has turned those files to 0 bytes. I could read each log before.

**Comment by wasdennnoch** [comment]
It is unlikely that is is caused by this module. All it does is to hook into the crash handler and execute some code to sent crash info to the app, no original code is changed. I don't know how Android handles the Dropbox, maybe on your device it is cleared upon reboot?

**Comment by malitech** [comment]
Oh yes, I supposed so, sorry.
But I could read it before. Don't know which module could cause it. I can't experiment it on my phone doing so many restarts. Anyway, thanks for the reply. :)
